Repository UCTalent/uc-ats-react-app, pull requests merged in 2024-10, with the labels that each got.

#38 UI Enhancements and Refactoring for Candidate Components
  src/components/common/user-avatar/UserAvatar.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/constants/STYLE.ts
  src/pages/TheJobCandidatePage.tsx
  src/theme/createTheme.ts
  src/utils/mockDndSceneV2.ts
Labels: enhancement, bug fix

#39 Refactor Layout Components and Update Routes
  src/components/sections/TheNavigateAsideCollapseBar.tsx
  src/components/sections/home/TopBarWithTitle.tsx
  src/components/sections/job-detail/TitleOverview.tsx
  src/components/subsections/home/TabsFilter.tsx
  src/layouts/AsideNavigateLayout.tsx
  src/layouts/JobDetailLayout.tsx
  src/layouts/app/AppLayout.tsx
  src/layouts/app/header-with-asidebar/_HeaderWithAsideBarLayout.tsx
  src/layouts/app/header-with-asidebar/index.ts
  src/layouts/app/header-with-asidebar/job-detail-header/__JobDetailHeaderLayout.tsx
  src/layouts/app/header-with-asidebar/job-detail-header/index.ts
  src/layouts/app/header-with-asidebar/job-detail-header/job-candidate-info/___JobCandidateInfoLayout.tsx
  src/layouts/app/header-with-asidebar/job-detail-header/job-candidate-info/index.ts
  src/layouts/app/index.ts
  src/pages/TheHomePage.tsx
  src/pages/TheJobDetailPage.tsx
  src/routes/Router.tsx
  src/routes/index.ts
  src/utils/mockDndSceneV2.ts
Labels: enhancement, Review effort [1-5]: 3, bug fix

#41 Refactor and enhance layout components and navigation bar
  src/components/sections/TheNavigateAsideBarCollapseExpand.tsx
  src/layouts/_app.tsx
  src/layouts/_base.tsx
  src/layouts/app/___job-detail-candidate-info.tsx
  src/layouts/app/__job-detail-header.tsx
  src/layouts/app/_app-header-with-aside-bar.tsx
  src/layouts/app/header-with-asidebar/index.ts
  src/layouts/app/header-with-asidebar/job-detail-header/index.ts
  src/layouts/app/header-with-asidebar/job-detail-header/job-candidate-info/index.ts
  src/layouts/app/index.ts
  src/routes/Router.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#42 Refactor component naming for consistency and clarity
  src/components/sections/AppHeader.tsx
  src/components/sections/NavigateAsideBar.tsx
  src/components/sections/NavigateAsideBarCollapseExpand.tsx
  src/components/sections/TheNavigateAsideCollapseBar.tsx
  src/components/subsections/job-detail/DndTriggerScrollContainers.tsx
  src/layouts/_base.tsx
  src/layouts/app/_app-header-with-aside-bar.tsx
Labels: enhancement, Review effort [1-5]: 2

#43 Enhance PopConfirm component with dynamic content rendering and update HTML sanitization
  src/components/common/PopConfirm.tsx
  src/components/common/TypographyHtml.tsx
  src/hooks/atoms/useConfirmAtom.ts
  src/hooks/useDndKanbanBoard.ts
  src/services/dnd/getChangeStatusWarningMessage.ts
  src/services/sanitizeHTML/sanitizeHTMLBasic.ts
  src/types/store/confirm.ts
Labels: enhancement, Review effort [1-5]: 3, bug fix

#45 Integrate Relay GraphQL and Update Project Configuration
  .env.example
  README.md
  package.json
  schema.graphql
  src/App.tsx
  src/components/common/LoadingSuspense.tsx
  src/constants/env.ts
  src/environment.ts
  src/pages/TheHomePage.tsx
  src/pages/__generated__/TheHomePageQuery.graphql.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: documentation, enhancement, Review effort [1-5]: 3, configuration changes

#46 Implement User Authentication with Login and Profile Fetching
  .env.example
  .gitignore
  package.json
  src/App.tsx
  src/assets/icons/eye-off.svg
  src/assets/icons/eye.svg
  src/components/common/ModalWithHeader.tsx
  src/components/common/form-fields/PasswordField.tsx
  src/components/common/user-avatar/UserAvatarWithChevron.tsx
  src/components/forms/LoginForm.tsx
  src/components/forms/index.ts
  src/components/sections/AppHeader.tsx
  src/constants/ENV_CONFIG.ts
  src/constants/FORM_DATA.ts
  src/constants/MODAL_ID.ts
  src/constants/env.ts
  src/environment.ts
  src/hooks/atoms/useCurrentUserAtom.ts
  src/hooks/atoms/useModalAtom.ts
  src/hooks/mutations/useMutateGetProfileMe.ts
  src/hooks/mutations/useMutateLoginWithEmail.ts
  src/pages/TheLoginPage.tsx
  src/providers/ModalProvider.tsx
  src/routes/Router.tsx
  src/services/api/auth.ts
  src/services/axios/axiosBasic.ts
  src/services/schema/formLogin.ts
  src/services/schema/formPostJob.ts
  src/store/confirmAtom.ts
  src/store/currentUserAtom.ts
  src/types/api/auth.ts
  src/types/api/index.ts
  src/types/forms/index.ts
  src/types/forms/login.ts
  src/types/forms/postJob.ts
  src/types/store/current-user.ts
  src/utils/cookie.ts
  src/vite-env.d.ts
  yarn.lock
Labels: enhancement, bug fix, Review effort [1-5]: 4

#47 Fix infinite profile fetch and enhance 401 error handling
  src/hooks/mutations/useMutateGetProfileMe.ts
  src/services/axios/axiosBasic.ts
Labels: bug fix, Review effort [1-5]: 2

#48 Fix infinite fetching issue in user profile mutation
  src/hooks/mutations/useMutateGetProfileMe.ts
Labels: bug fix, Review effort [1-5]: 2

#50 Enhance Login Page and App Header with Improved Layout and Features
  index.html
  public/uctalent.ico
  public/vite.svg
  src/assets/images/bg-talent.webp
  src/components/common/form-fields/PasswordField.tsx
  src/components/forms/LoginForm.tsx
  src/components/sections/AppHeader.tsx
  src/pages/TheLoginPage.tsx
Labels: documentation, enhancement

#51 Enhance styling for TheLoginPage components
  src/pages/TheLoginPage.tsx
Labels: enhancement, Review effort [1-5]: 1

#52 Fix navigation logic for login paths in PublicRoute component
  src/components/common/PublicRoute.tsx
Labels: bug fix, Review effort [1-5]: 1

#56 Implement User Logout and Enhance AppHeader UI
  src/components/common/PopConfirm.tsx
  src/components/common/TypographyHtml.tsx
  src/components/sections/AppHeader.tsx
  src/hooks/atoms/useCurrentUserAtom.ts
  src/hooks/useDndKanbanBoard.ts
Labels: enhancement, Review effort [1-5]: 3, bug fix

#57 Enhance job listing components with dynamic data fetching and display
  src/components/common/JobCard.tsx
  src/components/sections/AppHeader.tsx
  src/components/sections/home/TheJobsList.tsx
  src/constants/JOB.ts
  src/hooks/queries/__generated__/useJobsQuery.graphql.ts
  src/hooks/queries/useJobsQuery.ts
  src/pages/TheHomePage.tsx
  src/pages/__generated__/TheHomePageQuery.graphql.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#58 Implement Pagination for Job Listings and Enhance Loading Management
  src/App.tsx
  src/components/common/LoadingSuspense.tsx
  src/components/sections/home/FooterPagination.tsx
  src/hooks/queries/__generated__/useJobsQuery.graphql.ts
  src/hooks/queries/useJobsQuery.ts
  src/hooks/useJobsPagination.ts
  src/layouts/app/_app-header-with-aside-bar.tsx
  src/pages/TheHomePage.tsx
Labels: enhancement, Review effort [1-5]: 3, Tests

#59 Enhance job overview and implement job candidates query with state management
  schema.graphql
  src/components/sections/job-detail/TitleOverview.tsx
  src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
  src/hooks/queries/useJobCandidatesQuery.ts
  src/layouts/app/__job-detail-header.tsx
  src/pages/TheJobCandidatePage.tsx
  src/store/jobOverviewAtom.ts
  src/types/store/job-overview.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#64 Implement dynamic talent data fetching and rendering with GraphQL and Recoil
  src/components/common/user-avatar/UserAvatarWithDetails.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/hooks/queries/__generated__/useJobCandidateTalentSummaryQuery.graphql.ts
  src/hooks/queries/useJobCandidateTalentSummaryQuery.ts
  src/layouts/app/___job-detail-candidate-info.tsx
  src/pages/TheHomePage.tsx
  src/pages/job-candidate/TheJobCandidateSummaryPage.tsx
  src/store/talentOverviewAtom.ts
  src/types/store/talent-overview.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#65 Enhance job detail display with descriptive level mappings
  src/components/sections/job-detail/JobOverviewBox.tsx
  src/constants/JOB.ts
  src/pages/job-candidate/TheJobCandidateSummaryPage.tsx
Labels: enhancement, Review effort [1-5]: 2

#66 Enhance sidebar logic with home path detection
  src/layouts/app/_app-header-with-aside-bar.tsx
Labels: enhancement, Review effort [1-5]: 2

#67 Enhance job application status management and DnD functionality
  src/App.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/constants/JOB.ts
  src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
  src/hooks/queries/useJobCandidatesQuery.ts
  src/hooks/useDndKanbanBoard.ts
  src/pages/TheJobCandidatePage.tsx
  src/services/api/job-apply.ts
  src/services/job/candidates.ts
  src/types/api/job-apply.ts
Labels: enhancement, Review effort [1-5]: 3, bug fix

#68 Enhance candidate components and extend GraphQL schema and queries
  schema.graphql
  src/components/common/user-avatar/UserAvatarWithDetails.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/hooks/queries/__generated__/useJobCandidateTalentSummaryQuery.graphql.ts
  src/hooks/queries/useJobCandidateTalentSummaryQuery.ts
  src/pages/TheJobCandidatePage.tsx
Labels: enhancement, bug fix

#69 Add user profile photo functionality with avatar support
  src/components/sections/AppHeader.tsx
  src/hooks/mutations/useMutateGetProfileMe.ts
  src/types/store/current-user.ts
Labels: enhancement, Review effort [1-5]: 2

#70 Enhance logout process by clearing user data and redirecting to login
  src/hooks/atoms/useCurrentUserAtom.ts
Labels: Review effort [1-5]: 2, bug_fix

#71 Fix candidate status logic in CandidateStageColumnCard component
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
Labels: bug fix, Review effort [1-5]: 2

#72 Remove Apollo Client and related code from the project
  package.json
  src/providers/ApolloProvider.tsx
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 1

#73 Enhance Kanban board options and fix status message capitalization
  src/hooks/useDndKanbanBoard.ts
  src/pages/TheJobCandidatePage.tsx
  src/services/dnd/getChangeStatusWarningMessage.ts
  src/utils/index.ts
Labels: enhancement, bug fix, Review effort [1-5]: 2

#74 Fix job status key from `hire` to `hired` in constants
  src/constants/JOB.ts
Labels: Review effort [1-5]: 1, bug_fix

#75 Fix candidate status update from "hire" to "hired" in Kanban board
  src/hooks/useDndKanbanBoard.ts
Labels: bug fix, Review effort [1-5]: 1

#77 Add NavigateAsideCollapseBar component and fix time format in CandidateStageColumnCard
  src/components/sections/NavigateAsideCollapseBar.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
Labels: enhancement, bug fix, Review effort [1-5]: 2

#78 Enhance UI/UX with Suspense and Skeleton Loading Components
  src/App.tsx
  src/components/sections/job-detail/TitleOverview.tsx
  src/components/skeletons/JobTitleOverview.tsx
  src/layouts/app/___job-detail-candidate-info.tsx
  src/layouts/app/__job-detail-header.tsx
Labels: enhancement, Review effort [1-5]: 2

#79 Update default values for `currentUserAtom` in state management
  src/store/currentUserAtom.ts
Labels: enhancement, Review effort [1-5]: 1

#82 Integrate Blockchain Features and Enhance Job Management UI
  .env.example
  .gitpod.yml
  package.json
  src/App.tsx
  src/components/common/Alert.tsx
  src/components/common/BaseWallet/index.tsx
  src/components/common/Checkbox.tsx
  src/components/common/ModalCommon.tsx
  src/components/common/buttons/ButtonOutlined.tsx
  src/components/common/form-fields/CheckboxGroupField.tsx
  src/components/common/form-fields/TextField.tsx
  src/components/common/icons/AlertSuccess.tsx
  src/components/common/icons/CheckedCheckbox.tsx
  src/components/common/icons/UnCheckedCheckBox.tsx
  src/components/sections/AppHeader.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/home/modals/CloseJobFailed.tsx
  src/components/sections/home/modals/CloseJobSuccess.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/constants/ENV_CONFIG.ts
  src/constants/REASON_CLOSE_JOB_FAILED.ts
  src/hooks/abi/useCloseJobSmartContract.ts
  src/hooks/abi/useGetDecimalsToken.ts
  src/hooks/abi/useWriteContract.ts
  src/hooks/mutations/useMutateCancelJob.ts
  src/hooks/mutations/useMutateUpdateJobApplies.ts
  src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
  src/hooks/queries/useJobCandidatesQuery.ts
  src/libs/wagmiConfig.ts
  src/main.tsx
  src/pages/TheJobCandidatePage.tsx
  src/services/api/job.ts
  src/smart-contract/development/coreABI.ts
  src/smart-contract/development/tokenABI.ts
  src/store/alertAtom.ts
  src/types/api/job.ts
  src/types/common.ts
  src/types/store/alert.ts
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement, other, Review effort [1-5]: 4

#83 Optimize and Update GraphQL Query Structure in Generated File
  src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
Labels: enhancement, Review effort [1-5]: 2

#89 Enhance job filtering by status and introduce EmptyData component
  schema.graphql
  src/assets/images/juicy-girl-with-laptop.webp
  src/components/common/EmptyData.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/subsections/home/TabsFilter.tsx
  src/constants/JOB.ts
  src/hooks/queries/__generated__/useJobsQuery.graphql.ts
  src/hooks/queries/useJobsQuery.ts
  src/hooks/useJobsPagination.ts
  src/hooks/useJobsSearchParams.ts
  src/pages/TheHomePage.tsx
Labels: enhancement, bug fix

#90 Fix total page calculation for empty jobs case in TheHomePage
  src/pages/TheHomePage.tsx
Labels: bug fix, Review effort [1-5]: 1
