Repository UCTalent/uc-ats-react-app, pull requests merged in 2024-09, with the labels that each got.

#14 Implement Home Page Layout with New Components and Styling
  src/assets/icons/index.ts
  src/assets/icons/job-type.svg
  src/assets/icons/job.svg
  src/assets/icons/location.svg
  src/assets/icons/people.svg
  src/assets/icons/plus.svg
  src/assets/icons/store-box.svg
  src/components/common/CalendarBox.tsx
  src/components/common/JobCard.tsx
  src/components/common/UserAvatar.tsx
  src/components/common/WrappedSEO.tsx
  src/components/common/buttons/ButtonContained.tsx
  src/components/common/buttons/ButtonOutlined.tsx
  src/components/common/buttons/index.ts
  src/components/common/index.ts
  src/components/sections/TheAppHeader.tsx
  src/components/sections/TheNavigateAsideBar.tsx
  src/components/sections/common/index.ts
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/home/TopBarWithTitle.tsx
  src/components/sections/home/index.ts
  src/components/sections/index.ts
  src/pages/Home/index.tsx
  src/theme/createTheme.ts
  src/theme/type.ts
Labels: enhancement, Review effort [1-5]: 3, styling

#15 Implement Modal and Form Components for Job Posting
  package.json
  src/App.tsx
  src/assets/icons/ai-star.svg
  src/assets/icons/close.svg
  src/assets/icons/index.ts
  src/assets/icons/link.svg
  src/assets/icons/select-caret.svg
  src/components/common/IconSVG.tsx
  src/components/common/ModalWithHeader.tsx
  src/components/common/buttons/ButtonContained.tsx
  src/components/common/form-fields/AutocompleteField.tsx
  src/components/common/form-fields/NumberFormatField.tsx
  src/components/common/form-fields/RichTextEditor.tsx
  src/components/common/form-fields/SelectField.tsx
  src/components/common/form-fields/TextField.tsx
  src/components/common/form-fields/index.ts
  src/components/common/index.ts
  src/components/forms/PostJobForm.tsx
  src/components/forms/index.ts
  src/components/providers/ModalProvider.tsx
  src/components/providers/index.ts
  src/components/sections/home/TopBarWithTitle.tsx
  src/constants/MODAL_ID.ts
  src/hooks/atoms/index.ts
  src/hooks/atoms/useModalAtom.ts
  src/hooks/index.ts
  src/hooks/useDebounce.ts
  src/main.tsx
  src/store/example.ts
  src/store/modalAtom.ts
  src/types/common.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, bug fix, dependencies

#16 Refactor routing and form handling, add new layouts and utilities
  eslint.config.js
  package.json
  src/App.tsx
  src/components/common/WrappedSEO.tsx
  src/components/common/form-fields/AutocompleteField.tsx
  src/components/common/form-fields/NumberFormatField.tsx
  src/components/common/form-fields/RichTextEditor.tsx
  src/components/common/form-fields/TextField.tsx
  src/components/forms/PostJobForm.tsx
  src/components/forms/index.ts
  src/components/layouts/AsideNavigateLayout.tsx
  src/components/layouts/BaseLayout.tsx
  src/components/layouts/index.ts
  src/components/providers/ModalProvider.tsx
  src/components/sections/home/TopBarWithTitle.tsx
  src/constants/FORM_DATA.ts
  src/constants/META_SEO.ts
  src/constants/PAGE_MAP.ts
  src/constants/UCT_WEB.ts
  src/hooks/useScrollToTop.ts
  src/pages/Home/index.tsx
  src/pages/TheHomePage.tsx
  src/routes/RouteElement.tsx
  src/routes/index.ts
  src/routes/type.ts
  src/services/schema/formPostJob.ts
  src/services/schema/index.ts
  src/services/schema/resolver.ts
  src/types/common.ts
  src/types/forms/index.ts
  src/types/forms/postJob.ts
  src/utils/common.ts
  src/utils/messageRules.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement, bug fix, other, Review effort [1-5]: 4

#17 Implement Job Detail Page with New Components and Layout
  src/assets/icons/candidates.svg
  src/assets/icons/index.ts
  src/assets/icons/info.svg
  src/assets/icons/note.svg
  src/assets/icons/remote.svg
  src/assets/icons/salary.svg
  src/assets/icons/star.svg
  src/assets/icons/three-dots-vertical.svg
  src/assets/icons/thunder.svg
  src/components/common/Breadcrumbs.tsx
  src/components/common/DotDivider.tsx
  src/components/common/JobCard.tsx
  src/components/common/index.ts
  src/components/common/tags/BeautifulColorTag.tsx
  src/components/common/tags/RemoteTag.tsx
  src/components/common/tags/index.ts
  src/components/common/user-avatar/UserAvatar.tsx
  src/components/common/user-avatar/UserAvatarWithChevron.tsx
  src/components/common/user-avatar/index.ts
  src/components/layouts/JobDetailLayout.tsx
  src/components/layouts/index.ts
  src/components/sections/TheAppHeader.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/sections/job-detail/TabMenuHorizontal.tsx
  src/components/sections/job-detail/TitleOverview.tsx
  src/components/sections/job-detail/index.ts
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/components/subsections/job-detail/index.ts
  src/constants/PAGE_MAP.ts
  src/pages/TheJobDetailPage.tsx
  src/routes/index.ts
Labels: enhancement, other, Review effort [1-5]: 4

#20 Simplify Vite build script in package.json
  package.json
Labels: enhancement

#21 Integrate drag-and-drop functionality using react-smooth-dnd
  package.json
  src/assets/css/dnd.module.css
  src/components/common/dnd/DndContainer.tsx
  src/components/common/dnd/DndDraggable.tsx
  src/components/common/dnd/index.ts
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/sections/job-detail/TitleOverview.tsx
  src/hooks/useDndKanbanBoard.ts
  src/hooks/useHook.ts
  src/layouts/JobDetailLayout.tsx
  src/pages/TheJobDetailPage.tsx
  src/services/dnd/applyDrag.ts
  src/services/dnd/index.ts
  src/types/dnd.ts
  src/utils/bindClass.ts
  src/utils/mockDndScene.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, other

#22 Enhance job detail navigation and DnD functionality
  src/assets/icons/index.ts
  src/assets/icons/move-next.svg
  src/components/common/dnd/DndDraggable.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/job-detail/CandidateBoardToolBar.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/sections/job-detail/TabMenuHorizontal.tsx
  src/components/sections/job-detail/index.ts
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/constants/PAGE_MAP.ts
  src/hooks/useDndKanbanBoard.ts
  src/layouts/AsideNavigateLayout.tsx
  src/layouts/BaseLayout.tsx
  src/layouts/JobDetailLayout.tsx
  src/pages/TheJobCandidatePage.tsx
  src/pages/TheJobDetailPage.tsx
  src/pages/TheJobNotePage.tsx
  src/routes/index.ts
  src/types/dnd.ts
  src/utils/mockDndScene.ts
Labels: enhancement, Review effort [1-5]: 3, other

#23 Implement Job Detail Page with New Components and Enhancements
  package.json
  src/assets/css/app.css
  src/components/common/AppContainer.tsx
  src/components/common/TypographyHtml.tsx
  src/components/common/WrapperSection.tsx
  src/components/common/dnd/DndDraggable.tsx
  src/components/common/index.ts
  src/components/common/tags/BasicTag.tsx
  src/components/common/tags/index.ts
  src/components/sections/job-detail/JobDetailContent.tsx
  src/components/sections/job-detail/JobOverviewBox.tsx
  src/components/sections/job-detail/index.ts
  src/layouts/AsideNavigateLayout.tsx
  src/layouts/BaseLayout.tsx
  src/layouts/JobDetailLayout.tsx
  src/main.tsx
  src/pages/TheJobCandidatePage.tsx
  src/pages/TheJobDetailPage.tsx
  src/services/sanitizeHTML/index.ts
  src/services/sanitizeHTML/sanitizeHTMLBasic.ts
  yarn.lock
Labels: enhancement, bug fix, Review effort [1-5]: 4

#25 Enhance drag-and-drop components and optimize rendering performance
  src/assets/css/dnd.module.css
  src/components/common/dnd/DndContainer.tsx
  src/components/common/dnd/DndDraggable.tsx
  src/components/common/user-avatar/UserAvatar.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/hooks/useDndKanbanBoard.ts
  src/pages/TheJobCandidatePage.tsx
Labels: enhancement, bug fix

#26 Enhance drag-and-drop functionality and update mock data for CandidateStageColumn
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/constants/STYLE.ts
  src/hooks/useDndKanbanBoard.ts
  src/pages/TheJobCandidatePage.tsx
  src/types/dnd.ts
  src/utils/mockDndScene.ts
  src/utils/mockDndSceneV2.ts
Labels: enhancement, Review effort [1-5]: 3

#28 Enhance RichTextEditor and Rename Components for Consistency
  package.json
  src/assets/css/quill.module.scss
  src/components/common/ModalWithHeader.tsx
  src/components/common/WrapperSEO.tsx
  src/components/common/WrapperSectionContent.tsx
  src/components/common/form-fields/AutocompleteField.tsx
  src/components/common/form-fields/RichTextEditor.tsx
  src/components/common/form-fields/SelectField.tsx
  src/components/sections/job-detail/JobDetailContent.tsx
  src/components/sections/job-detail/TabMenuHorizontal.tsx
  src/hooks/useClickOutside.ts
  src/pages/TheJobNotePage.tsx
  src/routes/RouteElement.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, bug fix, other

#30 Refactor routing and enhance job candidate information display
  src/App.tsx
  src/assets/css/animation.module.scss
  src/assets/css/app.css
  src/assets/icons/back-arrow.svg
  src/components/common/ContainerRightSidePortalWithOverlay.tsx
  src/components/common/menus/MenuBasic.tsx
  src/components/common/tags/BasicTag.tsx
  src/components/common/user-avatar/UserAvatarWithDetails.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/sections/job-detail/TitleOverview.tsx
  src/components/sections/job-detail/job-candidate/TabMenuHorizontal.tsx
  src/components/subsections/job-detail/CandidateStageColumnCard.tsx
  src/constants/PAGE_MAP.ts
  src/hooks/useClickOutside.ts
  src/hooks/useDndKanbanBoard.ts
  src/layouts/AppLayout.tsx
  src/layouts/AsideNavigateLayout.tsx
  src/layouts/BaseLayout.tsx
  src/layouts/JobCandidateInfoLayout.tsx
  src/layouts/JobDetailLayout.tsx
  src/main.tsx
  src/pages/TheJobCandidatePage.tsx
  src/pages/job-candidate/TheJobCandidateJobListPage.tsx
  src/pages/job-candidate/TheJobCandidateNotePage.tsx
  src/pages/job-candidate/TheJobCandidateResumePage.tsx
  src/pages/job-candidate/TheJobCandidateSummaryPage.tsx
  src/routes/RouteElement.tsx
  src/routes/Router.tsx
  src/routes/index.ts
  src/routes/type.ts
  src/theme/createTheme.ts
Labels: enhancement, bug fix, other, Review effort [1-5]: 4

#32 Integrate Confirmation Modal and Enhance Drag-and-Drop Logic in Kanban Board
  src/App.tsx
  src/components/common/PopConfirm.tsx
  src/components/common/buttons/ButtonOutlined.tsx
  src/hooks/atoms/useConfirmAtom.ts
  src/hooks/useDndKanbanBoard.ts
  src/layouts/JobCandidateInfoLayout.tsx
  src/providers/PopConfirmProvider.tsx
  src/store/confirmAtom.ts
  src/types/dnd.ts
  src/types/store/confirm.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#33 Fix: Update `onClose` handler to cancel drag-and-drop in `PopConfirm` modal
  src/components/common/PopConfirm.tsx
Labels: bug fix, Review effort [1-5]: 1

#34 Fix jobId extraction from URL parameters in TabMenuHorizontal component
  src/components/sections/job-detail/TabMenuHorizontal.tsx
Labels: bug fix, Review effort [1-5]: 1

#35 Enhance UI/UX with new components and style updates
  src/assets/icons/three-dots-horizontal.svg
  src/components/common/JobCard.tsx
  src/components/common/tags/NumberWithLabelVerticalTag.tsx
  src/components/sections/TheAppHeader.tsx
  src/components/sections/TheNavigateAsideBar.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/subsections/home/TabsFilter.tsx
  src/constants/STYLE.ts
  src/theme/createTheme.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#37 UI/UX Enhancements and Custom Scrollbar Implementation
  src/components/common/JobCard.tsx
  src/components/common/dnd/DndContainer.tsx
  src/components/sections/TheAppHeader.tsx
  src/components/sections/TheNavigateAsideBar.tsx
  src/components/sections/home/TheJobsList.tsx
  src/components/sections/home/TopBarWithTitle.tsx
  src/components/sections/job-detail/CandidateStageColumn.tsx
  src/components/subsections/home/TabsFilter.tsx
  src/components/subsections/job-detail/DndTriggerScrollContainers.tsx
  src/layouts/AsideNavigateLayout.tsx
  src/layouts/JobDetailLayout.tsx
  src/pages/TheHomePage.tsx
  src/pages/TheJobCandidatePage.tsx
  src/pages/TheJobDetailPage.tsx
  src/pages/TheJobNotePage.tsx
  src/theme/createTheme.ts
  src/theme/type.ts
  src/utils/mockDndSceneV2.ts
Labels: enhancement, Review effort [1-5]: 3, bug fix
